services:
  app:
    container_name: ${ACTIVE_PROJECT}
    init: true
    environment:
      - $
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.12-bookworm
        ACTIVE_PROJECT: ${ACTIVE_PROJECT}
    volumes:
     - ../../${ACTIVE_PROJECT}:/workspaces/${ACTIVE_PROJECT}:cached
     # - ${PROJECT_ROOT}:/workspaces/${ACTIVE_PROJECT}:cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode